### ISSUE TITLE
Add filename to profiling stack trace

### ISSUE THREAD

**Issue by cmrigney** [keymetrics/keymetrics-support#100]
It would be useful to see the filename the function is in on the stack trace.

Currently looks like this:

![image](https://cloud.githubusercontent.com/assets/3259448/24295993/9c9915ca-1073-11e7-90d4-a0aa885ef75a.png)

**Comment by vmarchaud** [comment]
Thanks for the feedback, we opened an issue on our side.

**Comment by robin-monnier** [comment]
Implemented in the new UI: app.pm2.io
