### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by elliotfleming** [keymetrics/keymetrics-support#101]
I consistently experience a significant memory leak when I leave the dashboard open (will easily chew up any remaining memory until system becomes unstable - I've got 40GB).... didn't start until the new UI was rolled out. Let me know if you need anymore info! Best, Elliot

**Comment by vmarchaud** [comment]
Hello Elliot !

Could you take a memory snapshot and share it with us so we can investigate what are taking all the RAM please ?

**Comment by yleshchuk** [comment]
Can confirm. Reproducible in Chrome/Firefox.

**Comment by vmarchaud** [comment]
We are aware and working on a new frontend that will fix this issue, we do not plan to refactor the current frontend to avoid this problem.
