### ISSUE TITLE
Be able to retrieve and filter application logs

### ISSUE THREAD

**Issue by akaNightmare** [keymetrics/keymetrics-support#102]

**Comment by vmarchaud** [comment]
Hello,

I don't understand what you meant here ? What is `all logs` for you ?

Regards

**Comment by akaNightmare** [comment]
@vmarchaud all ~/.pm2/logs/*

**Comment by vmarchaud** [comment]
Keymetrics only provide way to see logs in realtime per application so they are already filtered ?

**Comment by akaNightmare** [comment]
@vmarchaud it would be great to have something like `kibana + logstash`

**Comment by vmarchaud** [comment]
Yeah we are aware that the log management side is missing but we need to put a lot of time into this feature, its definitely on the road-map but not before few months.

**Comment by vmarchaud** [comment]
We will not implement this in the SaaS version, checkout https://pm2.io/enterprise to get this feature
