### ISSUE TITLE
Transaction tracing is Loading

### ISSUE THREAD

**Issue by Farmazap** [keymetrics/keymetrics-support#106]
The screen does not exit the icon loading, I have waited 30 minutes and nothing
![loading](https://cloud.githubusercontent.com/assets/26315892/26476150/1ba46be4-4193-11e7-8917-726eeeb899d3.png)

**Comment by vmarchaud** [comment]
Hello, did you tried all steps described in the docs [here](http://docs.keymetrics.io/docs/pages/tracing/#throubleshooting) ? If its the case, could you share your module lists ? If not can you try them ?

**Comment by Farmazap** [comment]
Yes, I tested everything, which, I saw that you warned that the
request_promise is incompatible with the service, I use it only once in one
of my libs, the rest use http or the normal request. Attached is my list of
modules






Saudações,



*FarmaZap*
Todas as farmácias na sua mão



2017-05-26 5:27 GMT-03:00 vmarchaud <notifications@github.com>:

**Comment by vmarchaud** [comment]
@Farmazap Hello sorry for the delay i didn't saw the issue, sadly even when required by another dependency the behavior of this module is the same, it wipe the module cache so your modification isn't removed.
Can you try to requiring first the module that require `request_promise` and only then `pmx` ?

**Comment by vmarchaud** [comment]
https://github.com/keymetrics/keymetrics-support/issues/122
