### ISSUE TITLE
docker Identify service question 

### ISSUE THREAD

**Issue by leoliew** [keymetrics/keymetrics-support#108]
when i use pm2-docker to deploy my, i deploy two service in one machine, but keymetrics Identify as two server , have some wrong that i Set up ?

**Comment by vmarchaud** [comment]
Each container embed their own PM2 instance, they can't communicate outside of it (simply the way container works). So you can't really change this behavior

**Comment by leoliew** [comment]
So I bought eight servers plan, can only be 8 processes ?

**Comment by vmarchaud** [comment]
You can have as much servers as you can have processes, so its 8 indeed

**Comment by leoliew** [comment]
ok , I understand
