### ISSUE TITLE
Missing data from tracing dashboard

### ISSUE THREAD

**Issue by maximeloizeau** [keymetrics/keymetrics-support#113]
Hello,

I would like to report missing data on the tracing feature. For the same app, in one environment I can see the mean latency graph but not on another environment.

And also, on both environments I don't have any detail for the transactions, e.g. 
[sample screenshot](https://imgur.com/a/J9CLb)

My full list of dependencies https://pastebin.com/PKWeKUA1

I saw the troubleshooting FAQ and I put an import http after all request-native-promise imports like this:
```
import * as request from 'request-promise-native';  
import 'http';
```

And in my app entry file I put this, first line:
```
require('pmx').init({
  transactions : true
});
```
Since using the pm2.config.js didn't work to enable it.

Tell me if you need any info

**Comment by alavit-d** [comment]
Hi,

Unfortunately so far the tracing binds itself to the modules via `require`, and `import` is not supported. 
Which means to use the tracing you will need to use require in your project.

Let me know if you need more information

**Comment by maximeloizeau** [comment]
Thanks for the reply. I didn't know that.

However, this code is Typescript code that is being built to js and it generates require apparently:
```
const request = require("request-promise-native");
require("http");
```

Do you know if anything else from es6/typescript being compiled to es2015 that could cause any issue?

**Comment by vmarchaud** [comment]
Could you try launching your application with `DEBUG=vxx:*` and paste the logs here ? That would help us know whats going on thanks

**Comment by maximeloizeau** [comment]
Should I just put `vxx:*` in the DEBUG env variable? It doesn't seem to do anything to the logs.

I am using pm2 with pm2 logs to launch the application on AWS Beanstalk, it outputs to /var/log/nodejs/nodejs.log technically.

**Comment by maximeloizeau** [comment]
Hello @vmarchaud, please advise how I can help you debug my issues. If you can give me what the logging should look like when I enable the above DEBUG value, I can try to see what I get on my side.
Thank you

**Comment by vmarchaud** [comment]
https://github.com/keymetrics/keymetrics-support/issues/122
