### ISSUE TITLE
Keymetrics Module Interface Row Missplacement

### ISSUE THREAD

**Issue by spieglio** [keymetrics/keymetrics-support#114]
I just noticed that for some reason some columns are misplaced in the modules. It's always the Issues column. See screenshot.

I have my adblock disabled and can't think of anything else that it could be on my side.

Using latest Chrome, on Mac OS X.

<img width="1277" alt="keymetrics___app" src="https://user-images.githubusercontent.com/1096384/32478024-cfde3aba-c3b4-11e7-959d-7dbe154af929.png">

**Comment by vmarchaud** [comment]
Hello, i can't reproduce with our bucket, can you give me the link to yours ? Thanks

**Comment by spieglio** [comment]
Sure thing, this is the bucket that I am having the issue with:
https://app.keymetrics.io/#/bucket/5729c65227e2a5dd0518712c/dashboard

**Comment by alavit-d** [comment]
Hey, could you please try with private navigation to be sure no extension is messing with the display?

Thanks

**Comment by spieglio** [comment]
Ok, sorry for this. I found out that it's the `Evernote Web Clipper Version 6.13`. It's overwriting a CSS class apparently. I can't blame you guys for it, but maybe it's easier for you to fix it?

**Comment by alavit-d** [comment]
Glad we found the source! Unfortunately the extension is the one having the last say on CSS classes, please contact Evernote about this or if possible disable the extension on this page

Cheers

**Comment by spieglio** [comment]
I know this is not your responsibility - but would it be possible to change the class that's being overwritten by Evernote?

I'll also contact Evernote support to get this figured out.
