### ISSUE TITLE
Filters: filters are sometimes annoying

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#121]
When dashboard redirects the user in another section to get more details on a server, filters are written in the url.

It is annoying when the user wants to get a general view of the same section just after. The only way to make it is to remove the filters (that he is not aware of). Refreshing the browser or clicking in the browser doesn't remove the filter.

**Comment by vmarchaud** [comment]
Fixed with https://app.pm2.io
