### ISSUE TITLE
Filters: sometimes doesn't work

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#133]
After having redirected from Dashboard view to Monitoring view, refreshing the page makes the filter not applying the same way.

**Comment by vmarchaud** [comment]
not the  same as https://github.com/keymetrics/keymetrics-support/issues/121 ?

**Comment by rmonnier** [comment]
This one is a bug : refreshing the page makes it different.

#121 is more a comment about the way redirecting works, auto-applying filters that the user then have to manually remove to get a general view

**Comment by Unitech** [comment]
cannot reproduce the issue, when on a page and refreshing, filters are applied again
i need a recorded session to be able to really see the issue

**Comment by rmonnier** [comment]
Just checked on the customer bucket, fixed.
