### ISSUE TITLE
RT Logs: doesn't work

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#134]
The realtime logs (RT logs) doesn't work.

Additionally, there is a bug with the icon when clicking on the navbar.

**Comment by Unitech** [comment]
need to be able to reproduce this here, i've tried on official bucket + free bucket this error does not happen

icon has been fixed but w/o being able to reproduce the error, i cannot fix it
are you sure the remote interaction port is opened?
