### ISSUE TITLE
Logs before exception: sometimes only shows starting logs

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#135]
Logs before exception sometimes doesn't work and only shows starting logs.
This results in always display the same message every time an error occur.

**Comment by Unitech** [comment]
need to be able to reproduce this here, i've tried on official bucket + free bucket this error does not happen

**Comment by robin-monnier** [comment]
Ticket: #2145
5a0e61b5112a66f302b52408

**Comment by robin-monnier** [comment]
Will be fixed in next pm2 release

**Comment by daton89** [comment]
@robin-monnier patch or minor release?

**Comment by vmarchaud** [comment]
@daton89 next major (we are planning it for the next week)
