### ISSUE TITLE
Filters: not working on firefox

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#136]
On firefox, filters are not editable and display is bugged.

<img width="817" alt="capture d ecran 2018-01-24 a 17 36 06" src="https://user-images.githubusercontent.com/18701290/35344334-2fd85594-012d-11e8-984c-ecaa5cecf0d3.png">

**Comment by Unitech** [comment]
padding has been fixed, filter ares working, they are editable. need confirm

**Comment by daton89** [comment]
Now it works for me in firefox
