### ISSUE TITLE
UI: metrics in dashboard are constantly appearing/disappearing

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#139]
The network upload/download are constantly appearing and disappearing (due to 0 value) making columns jump around.

![screenshot-app keymetrics io-2018-01-26-23-47-31-452](https://user-images.githubusercontent.com/18701290/35504100-5c518efc-04e2-11e8-80e8-0e880b5047b4.png)
![screenshot-app keymetrics io-2018-01-26-23-48-45-487](https://user-images.githubusercontent.com/18701290/35504104-5dbeacd4-04e2-11e8-9c32-dc52f73434f7.png)

**Comment by vmarchaud** [comment]
Tracked here https://github.com/keymetrics/km-front/issues/254

**Comment by Unitech** [comment]
deployed
