### ISSUE TITLE
Process limitation: sometimes the processes are limited but they should not

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#141]
Sometimes the free plan limitation is bugged, resulting with a less than 4 processes monitoring possible.

Product team is aware of that problem, fix must be done soon.

**Comment by rmonnier** [comment]
+1

**Comment by rmonnier** [comment]
+1, with a pro_16

**Comment by Unitech** [comment]
@vmarchaud seems to be centralized on lambda node

**Comment by chemitaxis** [comment]
Same here in AWS. Elastic Beanstalk. Thanks.

**Comment by Unitech** [comment]
Hi,

I'm currently subscribed to the 8 process package, however I'm only able to view 4. Please assist.

regards,

**Comment by vmarchaud** [comment]
https://github.com/keymetrics/km-api/issues/450

**Comment by vmarchaud** [comment]
should be fixed
