### ISSUE TITLE
Navbar: jump when a subpart is open

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#149]
For example, if the user wants to click on notifications, there is a jump when hovering the navbar. See screenshots.

<img width="406" alt="capture d ecran 2018-02-06 a 13 10 22" src="https://user-images.githubusercontent.com/18701290/35859128-2f6ea998-0b3f-11e8-8976-8b0ab9469d17.png">
<img width="428" alt="capture d ecran 2018-02-06 a 13 10 31" src="https://user-images.githubusercontent.com/18701290/35859125-2f16548c-0b3f-11e8-937d-12eb28d034ea.png">

**Comment by vmarchaud** [comment]
Fixed with https://app.pm2.io
