### ISSUE TITLE
Pull, Rollback etc not showing

### ISSUE THREAD

**Issue by Trunken** [keymetrics/keymetrics-support#152]
Hi,

![image](https://user-images.githubusercontent.com/8668760/35861763-7b936980-0b49-11e8-881e-c78dd819b618.png)

My Keymetrics isnt showing the git pull buttons. What am I doing wrong?

**Comment by rmonnier** [comment]
Hi,

The buttons have indeed been temporarily disabled because they were making problems. You can find the related topic [here](https://github.com/keymetrics/keymetrics-support/issues/127).

They'll soon be working again.
