### ISSUE TITLE
Upgrade plan: wrong message

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#153]
If a user upgrade from yearly pro_8 to yearly pro_12, the message pre-payment doesn't take into account that he will only pay the difference.

See screenshot attached.

![keymetrics___app](https://user-images.githubusercontent.com/18701290/35907748-1be9b4c0-0bef-11e8-9690-4a503888dfef.png)

**Comment by vmarchaud** [comment]
Fixed with https://app.pm2.io
