### ISSUE TITLE
Mail notification: 'Invalid Date'

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#154]
Mail notifications for deployment have an issue with the date, displaying 'invalid date'.

<img width="718" alt="capture d ecran 2018-02-07 a 18 14 05" src="https://user-images.githubusercontent.com/18701290/35930634-bf82d6fa-0c32-11e8-8cab-a3fc6a8b65d3.png">

**Comment by vmarchaud** [comment]
Fixed with https://app.pm2.io
