### ISSUE TITLE
Realtime logs: doesn't work

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#155]
Doesn't work for these buckets:

https://app.keymetrics.io/#/bucket/59da4792b68a78f7215acc49/dashboard
https://app.keymetrics.io/#/bucket/5857a0199659911715cd2f17/dashboard

**Comment by Unitech** [comment]
(we can't do this because it requires permission)

**Comment by vmarchaud** [comment]
Should works better with new agent + websocket
