### ISSUE TITLE
Server seems offline: improvments required

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#156]
Constantly getting those pink messages: "Server seems offline. Latest update X minutes ago" with a "Delete Server" button.

As during development we are frequently updating services, every time we have to delete the server.

**Comment by Unitech** [comment]
feature dropped

**Comment by mscheffer** [comment]
if i understand this correctly you are just leaving those "servers" ?
now i have hundreds of apps that don't exist on my dashboard :)

i meant to say (in my original email) that i would prefer those "servers" to be removed automaticaly, like they are supposed to, without asking the user

we tried both settings, it just didn't work, by the way, it's a pitty someone has to be the owner of the bucket to activate this.

is there a way to tell keymetrics that the service (or server as you call it) is no longer active ?

**Comment by vmarchaud** [comment]
@mscheffer the title is confusing we are sorry about this. We removed the fact that the frontend is trying to guess without the backend if a server is offline.
We are working on getting the feature of offline servers back to production.

> we tried both settings, it just didn't work, by the way, it's a pitty someone has to be the owner of the bucket to activate this.

We are gonna decrease the required group to admin for enabling this feature, is it okay for you ?

> is there a way to tell keymetrics that the service (or server as you call it) is no longer active ?

We have an issue to had the possibility of sending a webhook to Keymetrics to warn it that a server is shutdown, but it's not a priority for now and it would be easier if keymetrics detected it itself.

**Comment by mscheffer** [comment]
seems good thanks

**Comment by vmarchaud** [comment]
@mscheffer The offline servers feature is working so the servers should disappear from the dashboard after few minutes after being disconnected if you set the option `Auto Server Deletion` in the bucket settings.

**Comment by mscheffer** [comment]
its working well now, thanks, merci

**Comment by mkpuig** [comment]
Hello, but the server is not really offline, so, if we auto delete server  this will not come back "magically" without login in onto de server ant linking it again. 
That's VERY annoying for a paid service :(
