### ISSUE TITLE
Transaction Tracing: time to wait after activation

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#164]
Just after activating the transaction for the first time, it is written to wait 1min but the timer isn't accurate at all.

After a refresh, it restarts and it takes way much longer than one minute.

No progression bar / better estimation would be better.

**Comment by vmarchaud** [comment]
Just revert this one https://github.com/keymetrics/km-front/commit/1c8377adcfcd45e3f9a08d33a51e1339caa8ceda
