### ISSUE TITLE
Heroku: Set the server name with PM2_MACHINE_NAME

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#168]
On Heroku, using the `PM2_MACHINE_NAME` environment variable inside an ecosystem file, in order to set the server name, doesn't work (process.env.PM2_MACHINE_NAME was however correctly set to the value).

This problem can be avoided using `heroku config:set PM2_MACHINE_NAME=my-app`.

**Comment by Unitech** [comment]
It is INSTANCE_NAME (we should bind to PM2_MACHINE_NAME though) https://github.com/Unitech/pm2/search?utf8=%E2%9C%93&q=INSTANCE_NAME&type=

**Comment by vmarchaud** [comment]
The agent can pickup name from `PM2_MACHINE_NAME` see https://github.com/Unitech/pm2/blob/master/lib/Interactor/Daemon.js#L206
