### ISSUE TITLE
Secret and public keys: same format

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#171]
All cloud providers use different size for public and private keys.

Different size makes keys easier to distinguish.

**Comment by rmonnier** [comment]
Also would be better to always display public and private in the same order. `pm2 link` takes `<secret> <public>` but at the top right of the dashboard it is displayed `public private`.

Public then private order is the most intuitive but the CLI is the hardest to change.

For now, everything should show secret then public.

**Comment by vmarchaud** [comment]
With websocket the agent will only need the private key
