### ISSUE TITLE
Upgrading: yearly/monthly switch

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#174]
- On the pricing tab, if a user clicks on the yearly/monthly switch button while the page is still loading, the switch is reset when the page is fully loaded. See this [fullstory session](https://app.fullstory.com/ui/29KMR/session/5678772424540160:5682751970738176!5629499534213120).

- Also, if a user wants to upgrade and add an additional credit card (but one has been already added), he is redirected to his billing page. The switch is then reset when he comes back to the pricing page.

**Comment by vmarchaud** [comment]
Fixed with app.pm2.io
