### ISSUE TITLE
Payment: Stripe token error

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#184]
When trying to subscribe, a customer has got a Stripe token error (see screenshot).

#2208
5ac1db7799b106ea8be8e27f
<img width="519" alt="capture d ecran 2018-04-03 a 13 38 52" src="https://user-images.githubusercontent.com/18701290/38247211-aca158bc-3744-11e8-87cb-e295970280e2.png">

**Comment by vmarchaud** [comment]
This mean the frontend has submitted twice the bucket upgrade request, so the second is automatically failling because the card token (that hold data) can only be used once.
