### ISSUE TITLE
how long can my app stay active once i turn off my laptop?: am a bit of a novice here, now trying it out.

### ISSUE THREAD

**Issue by AQUACY** [keymetrics/keymetrics-support#194]
am running an upvote bot on discord and  i want to keep it online 24/7. I have tried several free server but it seems the app goes offline once i leave their site and other sites too reset my bot token every 5 hours.

**Comment by robin-monnier** [comment]
Hi,

So, you are hosting a bot on a distant server and you've found out thanks to Keymetrics that your app goes offline after 5hours ? Have you found something abnormal happening on your dashboard ? If not, I won't really be able to help, it is probably related to the free plan you have with your servers.
