### ISSUE TITLE
"Alerts" always button in the way of uptime info. PM2 password + "Cannot POST" error.

### ISSUE THREAD

**Issue by Kovaelin** [keymetrics/keymetrics-support#198]
I took a screenshot to show you what I mean here: http://puu.sh/Ay6lw.png

It doesn't matter if I zoom in or out in my browser.

I also tried to set up alerts, and set up a PM2 password. However, when I input my password on Keymetrics, it gives me a small popup at the bottom, saying that it cannot post.

Also, what is the long chain of numbers ("values") that I get when I make a PM2 password? That also doesn't seem to work and gives me the same "cannot post" notification.

The app itself is running fine.

**Comment by vmarchaud** [comment]
Hello,

The alert system has been dropped because it was causing more problem than giving solution. We are working on a new one.
Note that you should checkout https://app.pm2.io to get a better UX

Regards
