### ISSUE TITLE
Run commands before running? (Or specify stuff via command line)

### ISSUE THREAD

**Issue by RyanCopley** [keymetrics/keymetrics-support#21]
Is it possible to have command-line functions ran before restarts, pulls, or etc? For example, 
`npm install`
or to do things like minifying CSS, etc?

also, I would like to be able to set environmental variables before running, so I can specify which environment the app should run as

**Comment by mikkotikkanen** [comment]
Personally, I got this working, however, in the context of npm and all, "postupdate" field name would make more sense (would follow the npm naming scheme). (you could have the "post_update" working as well for now and just change the documentation first)
