### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by btmdave** [keymetrics/keymetrics-support#39]
Hello,

Are there any docs on how the versioning works?  

Thank you

**Comment by Unitech** [comment]
We are going to do a real documentation at some point.
But here is some doc about this feature: https://github.com/Unitech/PM2/blob/master/doc/PULL.md

Best!

**Comment by btmdave** [comment]
Great, thanks.  So, we deploy by pushing to a bare git repo and use a post-receive hook, which checks out into another directory.  So pm2 is started from a directory that doesn't use git.  

Is there another method of deployment you recommend when using pm2?

So far keymetrics is working great btw!

**Comment by Unitech** [comment]
Thanks for these kind words :) We work hard on it to provide an unique monitoring experience :) 

When you do pm2 start app.js, it will use the folder of app.js to get versioning data (.git), is it ok for your usecase?

**Comment by btmdave** [comment]
The folder we do pm2 start app.js in, isn't a git repo.  It's just a directory that another bare git repo has a post-receive hook, so for example that hook does this `GIT_WORK_TREE=/var/www/AppFolder git checkout -f`, which checkouts the files into a non-git directory.

I guess we could do this differently, by having just a single git repo..

**Comment by Unitech** [comment]
@jorge-d what do you think?

**Comment by jorge-d** [comment]
Hi,

Well, the best way to enjoy the full capabilities of Keymetrics/PM2 would be to change your deployment process so that it uses the [pm2 deploy feature](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#deployment).

However we could eventually work in the future on a feature that would allow checking a git repo into another folder before running the process / getting the metadata, maybe be an option in the `ecosystem.json` file. @Unitech ?

**Comment by pjmartorell** [comment]
Hi, I have a question related to this issue. I have an app deployed on Heroku which uses PM2 as a module that programmatically starts my NodeJS app and communicates with keymetrics.io. I would like to enable the Versioning module of keymetrics.io but, as I know, it requires a .git repo in the folder of the app. Is there any way to programmatically specify the git repo to pull of? Thanks!

**Comment by Kovaelin** [comment]
Any updates on this issue?
