### ISSUE TITLE
error triggering events

### ISSUE THREAD

**Issue by ayxos** [keymetrics/keymetrics-support#42]
hallo, first of all, congratulations, with no doubts its the best monitoring tool that i've ever seen.

im having troubles when i try to create an event

```
var mongoose = require('mongoose'),
pmx = require('pmx').init(),
nodemailer     = require('nodemailer');

...

 exports.setPassword = function(req, res) {
   pmx.emit('pass: insert', {
     pass : req.body.code,
     ip : req.body.ip,
     result : (code == "mypass")
   });
  // some code
};

```

I dunno why but im not able to log this event on my keymetrics dahsboard.

What am i doing wrong?

Thanks

**Comment by jorge-d** [comment]
Hello @cybermarkus1,

I see nothing wrong with you snippet, can you try with the latest version of [pmx](https://github.com/keymetrics/pmx) and tell me whether it's working or not now?

Cheers

**Comment by jorge-d** [comment]
Ping ?

**Comment by Unitech** [comment]
fixed
