### ISSUE TITLE
Dashboard doesn't work with my server

### ISSUE THREAD

**Issue by anthonycluse** [keymetrics/keymetrics-support#48]
Hello,

I just launched the pm2 command to interact with the server but it seem's not working...

I have six apps when I do "pm2 list"...

Command on my server : pm2 interact *******\* *********
Result : [Keymetrics.io] Launched - Log: /home/anthoc/.pm2/agent.log | Conf: /home/anthoc/.pm2/agent.json | PID: /home/anthoc/.pm2/agent.pid

And after these commands I still have the same message on the dashboard "Congrats, you just created a new bucket!
Now link PM2 with Keymetrics to display the dashboard and features..."

Anthony

**Comment by Atelier-Morales** [comment]
Hi Anthony,
Fernan from Keymetrics here.
Are you behind a proxy? If so, that explains the problem, Keymetrics doesn't work with a proxy (this feature is currently under development). 
Could you please give us your Keymetrics id, username or email so that we can further investigate what's going on? Thank you.

**Comment by tonymx227** [comment]
Yes, my username : Icecom

And I'm not behind a proxy.

**Comment by Atelier-Morales** [comment]
Hey Anthony, Is your pm2 agent online? It will appear first when you do "pm2 list".

**Comment by tonymx227** [comment]
No, my pm2 agent is not in the list, how to proceed?

**Comment by jorge-d** [comment]
Could you try to update PM2 and tell us if it changes anything?

```shell
npm install pm2@latest -g && pm2 updatePM2
```

**Comment by tonymx227** [comment]
I updated PM2 with this command and now when I do "pm2 list", I get nothing in the list but all my app are online, I don't understand, I'm not able to see my apps in the list but they works....

**Comment by jorge-d** [comment]
Do you know which pm2 version you had before the upgrade?

**Comment by tonymx227** [comment]
No I don't remember, but how to delete all my apps? `pm2 delete all` doesn't work...

**Comment by jorge-d** [comment]
Got any error when running it?

**Comment by tonymx227** [comment]
No errors...

But I'm able to see my launched apps when running `pm2 ilogs`...

![ilogs](https://cloud.githubusercontent.com/assets/1122304/6595063/fb156b80-c7e6-11e4-8ce3-cf6542811fab.png)
![pm2list](https://cloud.githubusercontent.com/assets/1122304/6595064/fb222c4e-c7e6-11e4-9155-2376ad0af4ae.png)

**Comment by jshkurti** [comment]
It looks like a bug occured during the update.
Try `pkill -f node; pkill -f pm2; pm2 kill` :)

**Comment by tonymx227** [comment]
No, it doesn't work.
    
    anthoc@anthonycluseserver:~$ sudo pkill -f node; pkill -f pm2; pm2 kill
    pkill: killing pid 976 failed: Opération non permise
    [PM2] Spawning PM2 daemon
    [PM2] PM2 Successfully daemonized
    [PM2] Stopping PM2...
    [PM2][WARN] No process found
    [PM2] All processes has been stopped and deleted
    [PM2] PM2 stopped

**Comment by jshkurti** [comment]
Well, I'm afraid you are going to have to kill your processes manually this time.
It happens sometimes during pm2 update when versions differ a lot.

**Comment by tonymx227** [comment]
Doesn't work too : 

    anthoc@anthonycluseserver:~$ pm2 delete 0
    [PM2] Deleting 0 process
    [PM2][ERROR] Process 0 not found

**Comment by jshkurti** [comment]
By manually I meant with htop and kill ;)

**Comment by tonymx227** [comment]
Ok so now when I do `pm2 ilogs` I get nothing but all my apps can not be restarted status > `errored`...

**Comment by maxkueng** [comment]
I also had a problem where my server wouldn't show up on Keymetrics. It tuned out that I had accidentally installed pm2 twice in `/usr/bin` and `/usr/local/bin` and one of them was an older version (0.11). After I uninstalled pm2 through npm and than manually removed the second one and then reinstalled pm2@latest everything worked fine.

If you type `whereis pm2` do perhaps multiple locations show up?

**Comment by sergeikretov** [comment]
I also have a problem with my server showing on dashboard. 
Agent is running, only one pm2 is available, but on dashboard page I keep getting instructions how to link PM2 with Keymetrics to display the dashboard.

"pm2 list" output:
Agent online - public key: {my key here} - machine name: {my machine name here} - Web access: https://app.keymetrics.io/

**Comment by ImanMh** [comment]
I just installed pm2 and I have the same issue. my agent is online and I can see it's added in my settings tab but my dashboard is not displayed. 

os: Mac OS 10.10.5
﻿﻿→ node -v
v0.12.5
﻿﻿→ npm -v
3.5.0
﻿→ pm2 -v
1.0.0

**Comment by domarmstrong** [comment]
Same issue here. Server (my machine) is visible in settings but not on dashboard.

Ubuntu 14.04
pm2 1.1
node 5.9.0

**Comment by vmarchaud** [comment]
To anyone that still have this problem, please upgrade pm2 to the latest version and checkout that you can ping all ips defined [here](http://docs.keymetrics.io/docs/pages/faq-troubleshooting/#troubleshooting-for-keymetrics-pm2)
