### ISSUE TITLE
Plain text emails

### ISSUE THREAD

**Issue by maxkueng** [keymetrics/keymetrics-support#57]
Would be cool if there was a setting to change the preferred email type to plain text. I use Mutt and I have to launch an external program to view HTML emails.

Or perhaps it would be even better if the emails had both plain-text and HTML bodies so the email client can choose which body to display.

**Comment by Unitech** [comment]
@shubs interesting

**Comment by vmarchaud** [comment]
After discussing this internally we will not implement this.
