### ISSUE TITLE
Web hooks

### ISSUE THREAD

**Issue by maxkueng** [keymetrics/keymetrics-support#58]
Would be awesome we could provide URLs that would receive requests when certain events occur. Such as when a host goes offline, a program crashes, basically the things that currently trigger emails.

It would make it very easy to integrate with other services and notification systems.

**Comment by bendikl** [comment]
Second this one. You could build a nice ecosystem with partners just by opening up for custom http events like this. There is not much development to create readymade recipes for twilio, mailgun, boxcar or similar notification services.

**Comment by anthonyringoet** [comment]
Would love this

**Comment by crashbell** [comment]
:+1:

**Comment by aitorllj93** [comment]
:+1: 
Any new on this?

**Comment by jorge-d** [comment]
We're still on the process of thinking about this. It will happen, but I can't tell you when yet !

**Comment by crashbell** [comment]
@jorge-d thanks for considering it :)

**Comment by Unitech** [comment]
http://docs.keymetrics.io/docs/pages/integrations/
