### ISSUE TITLE
support for source maps in exceptions

### ISSUE THREAD

**Issue by hohl** [keymetrics/keymetrics-support#78]
I'm using Typescript to develop my Node.JS applications and so my source code is then compiled to Javascript. In addition to that the compiler creates source map, so that my IDE and Chrome Web Debugger knows which line of JS belongs to which line of TS. This makes stack traces much easier to read.
It would be nice if keymetrics.io would support that too in exceptions.

**Comment by Unitech** [comment]
fixed, update PM2
