### ISSUE TITLE
how to integrate with meteor.js ?

### ISSUE THREAD

**Issue by hems** [keymetrics/keymetrics-support#81]
Is there instructions for how to integrate with a meteor app?

considering an environment like: https://github.com/arunoda/meteor-up

**Comment by Unitech** [comment]
no idea

**Comment by Unitech** [comment]
https://www.npmjs.com/package/pm2-meteor

**Comment by hems** [comment]
@Unitech oh nice, very interesting stuff that pm2-meteor!

i will give it a go asap!

**Comment by hems** [comment]
@Unitech very kind of you to remember this issue and come back here! thanks a lot
