### ISSUE TITLE
Feature Request: Track all Express Route Requests

### ISSUE THREAD

**Issue by alanjames1987** [keymetrics/keymetrics-support#84]
I want to track when Express routes are requested so I can know when older versions of my APIs aren't being requested and I can deprecate them.

Currently I have to parse access logs to determine this, which is tedious.

It would be great if Keymetrics tracked this so I could determine it more easily.

**Comment by vmarchaud** [comment]
Hello,
Big bump because we recently developed a tracing feature : http://docs.keymetrics.io/docs/pages/tracing/

Feel free to test it and give us feedback :)
