### ISSUE TITLE
Feature Request: adding custom information to caught error

### ISSUE THREAD

**Issue by 4xoc** [keymetrics/keymetrics-support#89]
Basically, it would be great if I could add default information once an error has been caught that can be logged somewhere (best in the error description in the dashboard). This would be great to see what URL was called or user data being sent so that troubleshooting with this data is easier. Otherwise it the error messages aren't really helpfull at al without details on how to re-produce.

**Comment by Unitech** [comment]
@vmarchaud I guess it's now possible, closing

**Comment by vmarchaud** [comment]
http://docs.keymetrics.io/docs/usage/pmx-keymetrics-library/#add-verbosity-to-an-alert-express-error-handler
