### ISSUE TITLE
Clearing exceptions requires a hard refresh in dashboard

### ISSUE THREAD

**Issue by VMBindraban** [keymetrics/keymetrics-support#91]
If i clear the exceptions on the issues page i need to refresh the page to update the error count on the dashboard (sometimes a shift + crtl + r is needed).

The exceptions are from a node instance.

**Comment by vmarchaud** [comment]
Thanks for the feedback (and sorry for the delay), we have pushed an update that should have fixed that. 
If you still experimenting this issue, feel free to ping me.

**Comment by vmarchaud** [comment]
Published today with the new design !
