### ISSUE TITLE
App does not start with pm2 start command

### ISSUE THREAD

**Issue by giovanniroos** [keymetrics/keymetrics-support#92]
system info:
o/s: windows 7
node: 0.12.7
npm: 3.4.1
I have successfully installed pm2 with npm and uses your bufallo app. But the bufallo app does not start with ps2 from the commandline:

![image](https://cloud.githubusercontent.com/assets/846781/11294486/8ed6a404-8f6c-11e5-8b2b-3b0085b721ab.png)

If I use: node app.js then it starts up correctly and works correctly:

![image](https://cloud.githubusercontent.com/assets/846781/11294402/e1d28bb0-8f6b-11e5-8920-62f2c5638a27.png)

Here is a screen cap from the keymetrics dashboard:

![image](https://cloud.githubusercontent.com/assets/846781/11294489/9a9bf9c4-8f6c-11e5-9530-8fd7f4c1305c.png)

Which confims that there is no apps running.

What am I doing wrong?

Thank you

**Comment by sudeepdk** [comment]
update node version ...

**Comment by Unitech** [comment]
+1 + update pm2
