### ISSUE TITLE
HTTP analysis not working 

### ISSUE THREAD

**Issue by rohit-sourcefuse** [keymetrics/keymetrics-support#98]
I am using express as framework for making node server. I have follow the instruction mention here : 
http://docs.keymetrics.io/docs/pages/http/

But still i am seeing this page : 
![image](https://cloud.githubusercontent.com/assets/16935898/20970433/957fb064-bcb3-11e6-9186-15f30e98dcde.png)

Please help in and tell me how this work with express admin.

**Comment by vmarchaud** [comment]
Hello, you need to have a prenium account to use the transactions features.

**Comment by rohit-sourcefuse** [comment]
Hi @vmarchaud 
Thanks for your response. Can you explain this in little more detail ?
Because, i am not able to see any message saying this feature is part of premium account. Please let me know if this is the case because on **HTTP avg.** Option it showing enable and always showing "Enable HTTP analyes" button And also this option is not Disable like other premium options.

**Comment by vmarchaud** [comment]
The dashboard shouldn't allow you to come here in the first place, normaly you have a popup that explain it : http://imgur.com/a/EvuHX
