### ISSUE TITLE
Histogram API returns maximum of 10 probes, truncates the rest

### ISSUE THREAD

**Issue by cblanc** [keymetrics/keymetrics-support#99]
Hi there,

I found that the histograms API only returns 10 probes, and they aren't necessarily the same probes. For for the following endpoint `https://cassiope.keymetrics.io/api/bucket/<bucket_id>/data/probes/histogram` I'd get something like

```json
{
  "server_1": {
    "application_name": {
      "Metric #8": { ... },
      "Metric #12": { ... },
      "Metric #3": { ... },
      "Metric #1": { ... },
      "Metric #11": { ... },
      "Metric #17": { ... },
      "Metric #4": { ... },
      "Metric #7": { ... },
      "Metric #20": { ... },
      "Metric #19": { ... }
    }
  }
},
```

Would be great if you could return all of them at one go or provide an endpoint to query individual probe

**Comment by cblanc** [comment]
One more thing to clarify, I was under the impression that each server would return a random subset of metrics. 

However it turns out that this subset appears to be fixed and it also varies by server

**Comment by vmarchaud** [comment]
Sorry i forgot to look-up your problem, will do today.

**Comment by vmarchaud** [comment]
We found the problem last week, the fix is underway production, should be deployed around this week.
(sorry for the delay btw)

**Comment by cblanc** [comment]
Thanks for taking a look at this
